name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Felipecolare  # Seu username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz deploy para a branch output
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
